---

- name: Create ansible user
  user:
    name:        ansible
    group:       root
    home:        /home/ansible
    shell:       /bin/bash
    system:      no
    state:       present
    create_home: true


- name: create .ssh directory for ansible
  file: 
    path:   /home/ansible/.ssh
    state:  directory



